{"target": "tests/test_problem.py::test_exception_to_http_response_with_global_traceback", "type": "victim", "patch": false, "polluter": {"tests/test_problem.py::test_set_serialize_function": []}, "time": 12.701453685760498}